### PR TITLE
Ankush kafka 0.9

### PR DESCRIPTION
**Pull request by ankushgoyal**

### CODE REVIEW

**Comment by ankushgoyal** [comment]
@jontg - verified locally... and works perfectly - needed when running both kafka 0.8 and 0.9 and need to change the port of kafka 0.9 to something other than default.

**Comment by jontg** [comment]
Makes sense to me — is there anything we need to change in e.g. the graph docker-compose.yml before merging, or does the `edit_properties` shell command use sane defaults?  If it needs a default, we can always use bash defaults like:
```bash
${KAFKA_LISTENERS:-PLAINTEXT://:9092}
```

**Comment by jontg** [comment]
Demo of this in practice:
```bash
bash-4.3# echo ${VARIABLE:-PLAINTEXT://:9092}
PLAINTEXT://:9092
bash-4.3# VARIABLE=A_THING
bash-4.3# echo ${VARIABLE:-PLAINTEXT://:9092}
A_THING```

**Comment by jontg** [comment]
LGTM!  Nice work!

**Pull request merged**
